// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO1qVlIcXAbH68INkGh9ZqKGThJ941U-M',
    appId: '1:1010328868383:web:0e6e7b0db7796aef20e72a',
    messagingSenderId: '1010328868383',
    projectId: 'booking-961e0',
    authDomain: 'booking-961e0.firebaseapp.com',
    storageBucket: 'booking-961e0.appspot.com',
    measurementId: 'G-5GJ4JTM6QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsZPCnUVW_7gyHa_C6fzxmZQQcpBjAhjE',
    appId: '1:1010328868383:android:c32ff30d08cf610220e72a',
    messagingSenderId: '1010328868383',
    projectId: 'booking-961e0',
    storageBucket: 'booking-961e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6XuH0XR2OqxzqrVkm54BXwliOYBEa2S8',
    appId: '1:1010328868383:ios:3862039de88225fd20e72a',
    messagingSenderId: '1010328868383',
    projectId: 'booking-961e0',
    storageBucket: 'booking-961e0.appspot.com',
    iosBundleId: 'com.example.booking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6XuH0XR2OqxzqrVkm54BXwliOYBEa2S8',
    appId: '1:1010328868383:ios:3862039de88225fd20e72a',
    messagingSenderId: '1010328868383',
    projectId: 'booking-961e0',
    storageBucket: 'booking-961e0.appspot.com',
    iosBundleId: 'com.example.booking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO1qVlIcXAbH68INkGh9ZqKGThJ941U-M',
    appId: '1:1010328868383:web:9bedae2f53186f0720e72a',
    messagingSenderId: '1010328868383',
    projectId: 'booking-961e0',
    authDomain: 'booking-961e0.firebaseapp.com',
    storageBucket: 'booking-961e0.appspot.com',
    measurementId: 'G-P3ZGG6688T',
  );
}
